version: '3'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  python:
    image: "python-server"
    build: ./Python
    ports:
      - "8001:5432"

  node:
    image: "node-client"
    build: ./NodeJS
    links:
      - "python:server"
      - redis
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - REDIS_URL=redis://cache
      - NODE_ENV=development

networks:
  default:
    driver: bridge
